#啦啦啦
futurecode:
  secret: ${random.value}

  intran: ${random.int}

  server: www.futurecode.com

  desc: ${futurecode.server} is my server

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    time-zone: Asia/Chongqing
  profiles:

server:
  port: 80

logging:
  level: debug
  config: classpath:logback-futurecode.xml
  path: F:\\log
  #file: futurecode.log


---
spring:
  profiles: dev

server:
 port: 8082

---
spring:
  profiles: test

server:
 port: 8083

---
spring:
  profiles: pro

server:
 port: 8084
